sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-23
before_install:
- chmod +x gradlew
- echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script:
- ./gradlew clean assembleRelease
after_success:
- sh set_tags.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: lJnfVMlP/83zWQpHjqgf6xplAaaD9VFY3hd101+hxdOqVvVdm0gM2FC+PJHILn00rl9Q5sASyddI/rNQXdrOrY3HNC4AzelnZ+6MmXvu+xYdIbmXD2qVFep+mteHUcbyHoMesRnEotLTDgTZRoiIub+nC/cxp8DKvBOYI1vwYy7hvbl1W059yjWGPS0k/C2C+9IoktYDo6uFhgY+dzMfONWjIrATJlYF5dGH7m+VCsPs/kaoUR43qUi/FtfHWOgvh+AOnswCcrbQ76/tTCb7kIxHTPZw9hHpxNG0iW9KS0X/I5kqINit5feWu+j9EH/bOibjs4voKoxkVcCDiAO3cLOE3eLL7NgaShPxkPnwJQQeyRjtP/YBaxMjyRjx7rgXGH6i0yu+AKxZJFznGkE7HpzxMq5WTjKL0dNIVw2GtBnkJ2OIeQ5hRHyg1vghbeBPICiGi19yIv/mimqC4MCV7kOohnu0/PQy8mjOQi74AI2S2y+rgmk9egS4sW49XISd2SGbq7ec091D+xDJQZ4mCJXmNqXoN2LUPocdBAPHd3gsgE55oRCFiFfthBXXRRhfRVidvoHrn62O6xoHRMAfBpy5Gy87udzmOEmI4QWrHxlM53IWBLFzrNSqi+OWwbwoidYikAy9TQAjuppNcLnRC9KeIFMgeY+9KpbmDpcWykc=
  file_glob: "true"
  file: app/build/outputs/apk/release/app*release*.apk
  skip_cleanup: true
  on:
    branch: master
    repo: therickys93/wikiandroid
